select * from customer limit 20
--Q1. what is the total revenue generated by the male and female?
  SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;
--Q2. which customers used a discount but still spend more than the average purchasse amount?
   select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)
--Q3. which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating::numeric),2) as avg_review_rating
from customer 
group by item_purchased 
order by avg_review_rating desc limit 5;
--Q4 compare the average purchase amounts between standard and express shipping?
select shipping_type,round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
--Q5. do subscribed customers spend more? compare average spend and total revenue between subscribers and non subscribers?
select subscription_status,count(customer_id) as total_customers,
sum(purchase_amount) as total_revenue,round(avg(purchase_amount),2)as total_spend
from customer
group by subscription_status
order by total_revenue,total_spend
--Q6. which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5
--Q7 Segment customers into new ,returning and loyal based on their total number of previous purchases and show the count of each segment?
with customer_type as (
select customer_id,previous_purchases,
case
when previous_purchases =1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else loyal
end as customer_segment
from customer
)
select coustomer_segment ,count(*) as number_of_customers
from customer_type
gr
